name: "Build and Deploy to GitHub Pages"

on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    defaults:
      run:
        working-directory: ./social-network
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
#      - name: Run the tests and generate coverage report
#        run: npm test -- --coverage
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
      - name: Build
        run: npm run build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./social-network/build
